config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check
  root 'home#index'
  resources :products
  resources :barcodes
  resources :orders
  resources :clients

  get "orders/new/find/product" => "orders#find_product", as: :find_product
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :orders, dependent: :destroy

  enum status: { active: true, inactive: false }

  scope :active, -> { where(status: "active") }
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  def index
    @clients = Client.all
  end

  def show; end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)

    if @client.save
      flash[:success] = "Cliente criado com sucesso!"
    else
      flash[:error] = "Ocorreu um erro ao tentar criar o cliente: #{@client.errors.full_messages}"
    end

    redirect_to clients_url
  end

  def edit; end

  def update
    if @client.update(client_params)
      flash[:success] = "Cliente editado com sucesso!"
    else
      flash[:error] = "Ocorreu um erro ao tentar editar o cliente: #{@client.errors.full_messages}"
    end

    redirect_to clients_url
  end

  def destroy
    if @client.destroy!
      flash[:success] = "Cliente excluído com sucesso!"
    else
      flash[:error] = "Ocorreu um erro ao tentar excluir o cliente: #{@client.errors.full_messages}"
    end

    redirect_to clients_url
  end

  private
    def set_client
      @client = Client.find(params[:id])
    end

    def client_params
      attrs = params.require(:client).permit(
        :name,
        :identity_document_number,
        :phone_number,
        :birth_date,
        :zipcode,
        :street,
        :number,
        :complement,
        :neighborhood,
        :city,
        :state,
        :observations,
        :status
      )
      attrs[:status] = attrs[:status] == "false" ? false : true
      attrs
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <div class="row">
    <div class="col-6">
      <div class="input-group mb-3">
        <span class="input-group-text shadow shadow-sm">Nome</span>
        <%= form.text_field :name, class: "form-control shadow shadow-sm", required: true %>
      </div>

      <div class="input-group mb-3">
        <span class="input-group-text shadow shadow-sm">CPF</span>
        <%= form.text_field :identity_document_number, class: "form-control shadow shadow-sm", required: true %>
      </div>

      <div class="input-group mb-3">
        <span class="input-group-text shadow shadow-sm">Telefone</span>
        <%= form.text_field :phone_number, class: "form-control shadow shadow-sm", required: true %>
      </div>

      <div class="input-group mb-3">
        <span class="input-group-text shadow shadow-sm">Data de Nascimento</span>
        <%= form.date_field :birth_date, class: "form-control shadow shadow-sm", required: true %>
      </div>
      
      <div class="input-group mb-3">
        <span class="input-group-text shadow shadow-sm">Observations</span>
        <%= form.text_area :observations, class: "form-control shadow shadow-sm", rows: 4 %>
      </div>

      <div class="input-group mb-3">
        <span class="input-group-text shadow shadow-sm">Status</span>
        <%= form.select(
          :status, 
          options_for_select(
            Client.statuses.map { |s| [t(s[0]), s[1]] }, 
            @client.status
          )) 
        %>
      </div>
    </div>

    <div class="col-6 row">
      <div class="input-group mb-3 ">
        <span class="input-group-text shadow shadow-sm">CEP</span>
        <%= form.text_field :zipcode, class: "form-control shadow shadow-sm", required: true %>
      </div>

      <div class="input-group mb-3">
        <span class="input-group-text shadow shadow-sm">Rua</span>
        <%= form.text_field :street, class: "form-control shadow shadow-sm", required: true %>
      </div>

      <div class="input-group mb-3">
        <span class="input-group-text shadow shadow-sm">Número</span>
        <%= form.text_field :number, class: "form-control shadow shadow-sm", required: true %>
      </div>

      <div class="input-group mb-3">
        <span class="input-group-text shadow shadow-sm">Complemento</span>
        <%= form.text_field :complement, class: "form-control shadow shadow-sm" %>
      </div>

      <div class="input-group mb-3">
        <span class="input-group-text shadow shadow-sm">Bairro</span>
        <%= form.text_field :neighborhood, class: "form-control shadow shadow-sm", required: true %>
      </div>

      <div class="input-group mb-3">
        <span class="input-group-text shadow shadow-sm">Cidade</span>
        <%= form.text_field :city, class: "form-control shadow shadow-sm", required: true %>
      </div>

      <div class="input-group mb-3">
        <span class="input-group-text shadow shadow-sm">Estado</span>
        <%= form.text_field :state, class: "form-control shadow shadow-sm", required: true %>
      </div>
    </div>
  </div>

  <div>
    <%= link_to "Voltar", clients_path, class:"btn btn-outline-secondary" %>
    <%= form.submit "#{@client.persisted? ? "Atualizar" : "Cadastrar"}", class: "btn btn-primary" %>
  </div>
<% end %>

<script>
  $('#client_identity_document_number').mask("000.000.000-00");
  $('#client_phone_number').mask("(00) 00000-0000");
  $('#client_zipcode').mask("00000-000");
  $('#client_status').attr("class", "form-select");

</script>

app/views/clients/edit.html.erb
<h1>Editar Cliente</h1>

<%= render "form", client: @client %>

<br>

app/views/clients/index.html.erb
<div class="row">
  <div class="col-10">
    <h1>Clientes</h1>
  </div>
  <div class="col-2">
    <%= link_to "Novo", new_client_path, class: "btn btn-primary float-end" %>
  </div>
</div>
<hr>
<table class="table table-striped shadow">
  <thead>
    <tr>
      <th>Criado em</th>
      <th>Nome</th>
      <th>CPF</th>
      <th>Telefone</th>
      <th>Data de Nascimento</th>
      <th>Status</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.created_at.strftime("%d/%m/%Y %H:%M") %></td>
        <td><%= link_to client.name, edit_client_path(client) %></td>
        <td><%= client.identity_document_number %></td>
        <td><%= client.phone_number %></td>
        <td><%= client.birth_date.strftime("%d/%m/%Y") %></td>
        <td><%= t(client.status) %></td>
        <td>
          <%= button_to client_path(client), method: :delete, class: "btn btn-outline-danger" do %>
            <i class="bi bi-power"></i>
          <% end  %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/clients/new.html.erb
<h1>Novo Cliente</h1>

<%= render "form", client: @client %>

<br>