config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check
  root 'home#index'
  resources :products
  resources :barcodes
  resources :orders
  resources :clients

  get "orders/new/find/product" => "orders#find_product", as: :find_product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :client

  after_create :set_total

  enum status: { pending: "pending", on_delivery_route: "on_delivery_route", delivered: "delivered" }

  private

  def set_total
    self.update(total_price_in_cents: ((self.product.price_in_cents * 100).to_i * self.quantity))
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]

  def index
    @orders = Order.all.order("created_at DESC")
  end

  def show; end

  def find_product
    render json: Product.find(params[:product_id]).quantity
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)

    product = Product.find(params[:order][:product_id])
    product_quantity = product.quantity

    if @order.save! && product.update(quantity: (product_quantity - params[:order][:quantity].to_i))
      product.update(status: "in_stock") if product.quantity >= 20
      product.update(status: "low_stock") if product.quantity < 20
      product.update(status: "out_of_stock") if product.quantity == 0
      flash[:success] = "Encomenda criada com sucesso!"
    else
      flash[:error] = "Ocorreu um erro ao tentar criar a Encomenda: #{@order.errors.full_messages}"
    end

    redirect_to orders_path
  end

  def edit; end

  def update
    if @order.update(order_params)
      flash[:success] = "Encomenda atualizada com sucesso!"
    else
      flash[:error] = "Ocorreu um erro ao tentar atualizar a Encomenda: #{@order.errors.full_messages}"
    end

    redirect_to orders_path
  end

  def destroy
    product = @order.product
    product_quantity = product.quantity

    if @order.destroy! && product.update(quantity: (product_quantity + @order.quantity))
      product.update(status: "in_stock") if product.quantity >= 20
      product.update(status: "low_stock") if product.quantity < 20
      product.update(status: "out_of_stock") if product.quantity == 0
      flash[:success] = "Encomenda excluído com sucesso!"
    else
      flash[:error] = "Ocorreu um erro ao tentar excluir a Encomenda: #{@order.errors.full_messages}"
    end

    redirect_to orders_path
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      attrs = params.require(:order).permit(
        :product_id,
        :client_id,
        :quantity,
        :status
      )
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <div class="row">
    <div class="col-6">
      <div class="input-group mb-3">
        <span class="input-group-text shadow shadow-sm">Produto</span>
        <%= form.select(
          :product_id, 
          options_for_select(
            Product.available_products.with_barcode.map { |k| ["#{k.name} | #{k.quantity} unidade(s) disponível(is)", k.id] }, 
            @order.product_id
          ), 
          { include_blank: 'Selecione o Produto' }, 
          class: "form-select", required: true ) 
        %>
      </div>

      <div class="input-group mb-3">
        <span class="input-group-text shadow shadow-sm">Quantidade</span>
        <%= form.number_field :quantity, class: "form-control shadow shadow-sm", min: 1, required: true %>
      </div>

      <div class="input-group mb-3">
        <span class="input-group-text shadow shadow-sm">Cliente</span>
        <%= form.select(
          :client_id, 
          options_for_select(
            Client.active.map { |k| [k.name, k.id] },
            @order.client_id
          ), 
          { include_blank: 'Selecione o Cliente' }, 
          class: "form-select", required: true ) 
        %>
      </div>

      <div class="input-group mb-3">
        <span class="input-group-text shadow shadow-sm">Status</span>
        <%= form.select(
          :status, 
          options_for_select(
            @order.persisted? ? (Order.statuses.select { |status| status != "pending" }.map { |k| [t(k[0]), k[1]] }) : (Order.statuses.map { |k| [t(k[0]), k[1]] }), 
            @order.status
          ), 
          { include_blank: 'Selecione o status' }, 
          class: "form-select", required: true ) 
        %>
      </div>
    </div>
  </div>

  <div>
    <%= link_to "Voltar", orders_path, class:"btn btn-outline-secondary" %>
    <%= form.submit "#{@order.persisted? ? "Atualizar" : "Cadastrar"}", class: "btn btn-primary" %>
  </div>
<% end %>

<script>
  `<% if @order.persisted? %>`
    $("#order_product_id").attr("disabled", true);
    $("#order_client_id").attr("disabled", true);
    $("#order_quantity").attr("disabled", true);
  `<% end %>`

  $("#order_product_id").focusout(function() {
    $.ajax({
      type: "GET",
      url: "<%= find_product_path %>",
      data: {
        product_id: $("#order_product_id").val()
      },
      success: function(response) {
        var quantity = parseInt(response)
        $("#order_quantity").attr("max", quantity);

        var mask_numbers = ""
        for (let i = 0; i < response.toString().split('').map(Number).length; i++) {
          mask_numbers = mask_numbers + "0"
        }
        $('#order_quantity').mask(mask_numbers);
      }
    });
  });
</script>

app/views/orders/edit.html.erb
<h1>Editar Encomenda</h1>

<%= render "form", order: @order %>

<br>

app/views/orders/index.html.erb
<div class="row">
  <div class="col-10">
    <h1>Encomendas</h1>
  </div>
  <div class="col-2">
    <%= link_to "Novo", new_order_path, class: "btn btn-primary float-end" %>
  </div>
</div>
<hr>
<table class="table table-striped shadow">
  <thead>
    <tr>
      <th>Criado em</th>
      <th>Produto</th>
      <th>Código de Barras</th>
      <th>Cliente</th>
      <th>Quantidade</th>
      <th>Valor total</th>
      <th>Status</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to order.created_at.strftime("%d/%m/%Y %H:%M"), edit_order_path(order) %></td>
        <td><%= order.product.name %></td>
        <td><%= order.product.barcode.number %></td>
        <td><%= order.client.identity_document_number %></td>
        <td><%= order.quantity %></td>
        <td><%= number_to_currency((order.total_price_in_cents / 100) || 0) %></td>
        <td><%= t(order.status) %></td>
        <td>
          <%= button_to order_path(order), method: :delete, class: "btn btn-outline-danger" do %>
            <i class="bi bi-power"></i>
          <% end if order.status == "pending"  %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/new.html.erb
<h1>Nova Encomenda</h1>

<%= render "form", order: @order %>

<br>