config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check
  root 'home#index'
  resources :products
  resources :barcodes
  resources :orders
  resources :clients

  get "orders/new/find/product" => "orders#find_product", as: :find_product
end

app/models/barcode.rb
class Barcode < ApplicationRecord
  belongs_to :product
end

app/controllers/barcodes_controller.rb
class BarcodesController < ApplicationController
  before_action :set_barcode, only: %i[ show edit update destroy ]

  def index
    @barcodes = Barcode.all.order("created_at DESC")
  end

  def show; end

  def new
    @barcode = Barcode.new
  end

  def edit; end

  def create
    @barcode = Barcode.new(barcode_params)

    if @barcode.save!
      flash[:success] = "Código de Barras criado com sucesso!"
    else
      flash[:error] = "Ocorreu um erro ao tentar criar o Código de Barras: #{@barcode.errors.full_messages}"
    end

    redirect_to barcodes_url
  end

  def update
    product = Product.find(params[:barcode][:product_id])

    return (
      flash[:error] = "Não foi possível adicionar o produto #{product.name} pois ele já pertence ao código de barras #{product.barcode.number}"
      redirect_to edit_barcode_url(@barcode)
    ) if product.barcode.present? && product.barcode.number != params[:barcode][:number]

    if @barcode.update(barcode_params)
      flash[:success] = "Código de Barras atualizado com sucesso!"
    else
      flash[:error] = "Ocorreu um erro ao tentar atualizar o Código de Barras: #{@barcode.errors.full_messages}"
    end

    redirect_to barcodes_url
  end

  def destroy
    if @barcode.destroy!
      flash[:success] = "Código de Barras excluído com sucesso!"
    else
      flash[:error] = "Ocorreu um erro ao tentar excluir o Código de Barras: #{@barcode.errors.full_messages}"
    end

    redirect_to barcodes_url
  end

  private
    def set_barcode
      @barcode = Barcode.find(params[:id])
    end

    def barcode_params
      params.require(:barcode).permit(
        :product_id,
        :number,
        :status
      )
    end
end

app/helpers/barcodes_helper.rb
module BarcodesHelper
end

app/views/barcodes/_form.html.erb
<%= form_with(model: barcode) do |form| %>
  <div class="row">
    <div class="col-6">
      <div class="input-group mb-3">
        <span class="input-group-text shadow shadow-sm">Número</span>
        <%= form.text_field :number, class: "form-control shadow shadow-sm", required: true %>
      </div>

      <div class="input-group mb-3">
        <span class="input-group-text shadow shadow-sm">Produto</span>
        <%= form.select(
          :product_id, 
          options_for_select(
            Product.all.map { |k| [k.name, k.id] }, 
            @barcode.product_id
          ), 
          { include_blank: 'Selecione o Produto' }, 
          class: "form-select", required: true ) 
        %>
      </div>
    </div>
  </div>

  <div>
    <%= link_to "Voltar", barcodes_path, class:"btn btn-outline-secondary" %>
    <%= form.submit "#{@barcode.persisted? ? "Atualizar" : "Cadastrar"}", class: "btn btn-primary" %>
  </div>
<% end %>

<script>
  $('#barcode_number').mask("00000000000000000000000000000000");
</script>

app/views/barcodes/edit.html.erb
<h1>Editar Código de Barras</h1>

<%= render "form", barcode: @barcode %>

<br>

app/views/barcodes/index.html.erb
<div class="row">
  <div class="col-10">
    <h1>Códigos de Barras</h1>
  </div>
  <div class="col-2">
    <%= link_to "Novo", new_barcode_path, class: "btn btn-primary float-end" %>
  </div>
</div>
<hr>
<table class="table table-striped shadow">
  <thead>
    <tr>
      <th>Criado em</th>
      <th>Número</th>
      <th>Produto</th>
      <th>Status</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @barcodes.each do |barcode| %>
      <tr>
        <td><%= barcode.created_at.strftime("%d/%m/%Y %H:%M") %></td>
        <td>
          <%= link_to barcode.number, edit_barcode_path(barcode) if barcode.status %>
          <%= barcode.number unless barcode.status %>
        </td>
        <td><%= link_to barcode.product.name, edit_product_path(barcode.product) %></td>
        <td><%= barcode.status ? "Ativo" : "Inativo" %></td>
        <td>
          <% if barcode.status %>
            <%= button_to barcode_path(barcode), method: :delete, class: "btn btn-outline-danger" do %>
              <i class="bi bi-trash"></i>
            <% end %>
          <% else %>
            Indisponível
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/barcodes/new.html.erb
<h1>Novo Código de Barras</h1>

<%= render "form", barcode: @barcode %>

<br>