config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check
  root 'home#index'
  resources :products
  resources :barcodes
  resources :orders
  resources :clients

  get "orders/new/find/product" => "orders#find_product", as: :find_product
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :description, :quantity, :price_in_cents, presence: true

  has_one :barcode, dependent: :destroy

  has_many :orders, dependent: :destroy

  enum status: { in_stock: "in_stock", low_stock: "low_stock", out_of_stock: "out_of_stock" }

  scope :with_no_barcode, -> { select{ |product| product.barcode.nil? }}
  scope :with_barcode, -> { select{ |product| product.barcode.present? }}
  scope :available_products, -> { where(status: ["in_stock", "low_stock"]).where("quantity >= 1")}
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  def index
    @products = Product.all.order("created_at DESC")
  end

  def show; end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      @product.update(status: "in_stock") if @product.quantity >= 20
      @product.update(status: "low_stock") if @product.quantity < 20
      @product.update(status: "out_of_stock") if @product.quantity == 0

      flash[:success] = "Produto criado com sucesso!"
    else
      flash[:error] = "Ocorreu um erro ao tentar criar o produto: #{@product.errors.full_messages}"
    end

    redirect_to products_url
  end

  def edit; end

  def update
    if @product.update(product_params)
      @product.update(status: "in_stock") if @product.quantity >= 20
      @product.update(status: "low_stock") if @product.quantity < 20
      @product.update(status: "out_of_stock") if @product.quantity == 0

      flash[:success] = "Produto atualizado com sucesso!"
    else
      flash[:error] = "Ocorreu um erro ao tentar atualizar o produto: #{@product.errors.full_messages}"
    end

    redirect_to products_url
  end

  def destroy
    if @product.destroy!
      flash[:success] = "Produto excluído com sucesso!"
    else
      flash[:error] = "Ocorreu um erro ao tentar excluir o produto: #{@product.errors.full_messages}"
    end

    redirect_to products_url
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      attrs = params.require(:product).permit(
        :name,
        :description,
        :quantity,
        :price_in_cents,
        :status
      )

      attrs[:price_in_cents] = attrs[:price_in_cents].gsub('.', '').gsub(',', '').to_f / 100.0

      attrs
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <div class="row">
    <div class="col-6">
      <div class="input-group mb-3">
        <span class="input-group-text shadow shadow-sm">Nome</span>
        <%= form.text_field :name, class: "form-control shadow shadow-sm", required: true %>
      </div>

      <div class="input-group mb-3">
        <span class="input-group-text shadow shadow-sm">Descrição</span>
        <%= form.text_field :description, class: "form-control shadow shadow-sm", required: true %>
      </div>

      <div class="input-group mb-3">
        <span class="input-group-text shadow shadow-sm">Quantidade</span>
        <%= form.number_field :quantity, class: "form-control shadow shadow-sm", max: 500, min: 0, required: true %>
      </div>

      <div class="input-group mb-3">
        <span class="input-group-text shadow shadow-sm">R$</span>
        <%= form.text_field :price_in_cents, class: "form-control shadow shadow-sm", value: @product.persisted? ? (@product.price_in_cents) : "", required: true %>
      </div>
    </div>
  </div>

  <div>
    <%= link_to "Voltar", products_path, class:"btn btn-outline-secondary" %>
    <%= form.submit "#{@product.persisted? ? "Atualizar" : "Cadastrar"}", class: "btn btn-primary" %>
  </div>
<% end %>

<script>
  $('#product_quantity').mask("000");
  $('#product_price_in_cents').mask("000.000.000,00", {reverse: true});
</script>

app/views/products/edit.html.erb
<h1>Editar Produto</h1>

<%= render "form", product: @product %>

<br>

app/views/products/index.html.erb
<div class="row">
  <div class="col-10">
    <h1>Produtos</h1>
  </div>
  <div class="col-2">
    <%= link_to "Novo", new_product_path, class: "btn btn-primary float-end" %>
  </div>
</div>
<hr>
<table class="table table-striped shadow">
  <thead>
    <tr>
      <th>Criado em</th>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Quantidade</th>
      <th>Preço (unidade)</th>
      <th>Status</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.created_at.strftime("%d/%m/%Y %H:%M") %></td>
        <td><%= link_to product.name, edit_product_path(product) %></td>
        <td><%= product.description %></td>
        <td><%= product.quantity %></td>
        <td><%= number_to_currency(product.price_in_cents) %></td>
        <td><%= t(product.status) %></td>
        <td>
          <%= button_to product_path(product), method: :delete, class: "btn btn-outline-danger" do %>
            <i class="bi bi-trash"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h1>Novo Produto</h1>

<%= render "form", product: @product %>

<br>